name: Luacheck

on: [push, pull_request]

jobs:

  luacheck:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Luacheck
        uses: lunarmodules/luacheck@v1
