name: Versioning

on:
  release:
    types: [ created, published, edited ]

jobs:
  actions-tagger:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Update release tags
        uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: true
