describe("Tests to make sure the say library is functional", function()
  local s = require('say.s')

  it("tests the set function metamethod", function()
    s:set('herp', 'derp')
    assert(s.registry.__g.herp == 'derp')

    s:set('herp', 'derp', 'foo')
    assert(s.registry.herp.derp == 'foo')
  end)

  it("tests the __call metamethod", function()
    assert(s('herp') == 'derp')
    assert(s('herp', 'derp') == 'foo')
    s:set('herp', 'derp', '%s')
    assert(s('herp', 'derp', {'test'}) == 'test')
    s:set('herp', '%s')
    assert(s('herp', {'test'}) == 'test')
    s:set('herp', '%s%s')
    assert(s('herp', {'test', 'test'}) == 'testtest')
  end)
end)
